USE ROLE SYSADMIN;
USE DATABASE QUERY_API_STARTER;
USE SCHEMA INGEST;

SELECT CONFIG_ID, SETTINGS FROM INGEST_CONFIG;
SELECT * FROM INGEST_RUNS ORDER BY STARTED_AT DESC;
SELECT * FROM INGEST_LOCK;
SELECT * FROM LATEST_RECORDS LIMIT 20;

SELECT
    PAYLOAD:polygon_id::VARCHAR AS POLYGON_ID,
    PAYLOAD:layer::VARCHAR AS LAYER,
    PAYLOAD:unit_name::VARCHAR AS UNIT_NAME,
    PAYLOAD:lithology::VARCHAR AS LITHOLOGY,
    PAYLOAD:centroid_lon::DOUBLE AS CENTROID_LON,
    PAYLOAD:centroid_lat::DOUBLE AS CENTROID_LAT,
    PAYLOAD:geometry_wkt::VARCHAR AS GEOMETRY_WKT,
    PAYLOAD:geom::VARCHAR AS GEOM,
    RUN_ID,
    INGESTED_AT
FROM LATEST_RECORDS
LIMIT 100;

SELECT NAME, STATE, SCHEDULED_TIME, COMPLETED_TIME, ERROR_MESSAGE
FROM TABLE(SNOWFLAKE.INFORMATION_SCHEMA.TASK_HISTORY(
    TASK_NAME => 'QUERY_API_POLL',
    SCHEDULED_TIME_RANGE_START => DATEADD('day', -7, CURRENT_TIMESTAMP()),
    SCHEDULED_TIME_RANGE_END => CURRENT_TIMESTAMP(),
    RESULT_LIMIT => 10000
))
WHERE DATABASE_NAME = 'QUERY_API_STARTER' AND SCHEMA_NAME = 'INGEST'
ORDER BY SCHEDULED_TIME DESC;
