USE ROLE SYSADMIN;

CREATE DATABASE IF NOT EXISTS QUERY_API_STARTER;
CREATE SCHEMA IF NOT EXISTS QUERY_API_STARTER.INGEST;
USE DATABASE QUERY_API_STARTER;
USE SCHEMA INGEST;

CREATE TABLE INGEST_CONFIG (
    CONFIG_ID NUMBER NOT NULL,
    SETTINGS VARIANT NOT NULL
);

INSERT INTO INGEST_CONFIG
SELECT 1, PARSE_JSON($${{CONFIG_JSON}}$$);

CREATE TABLE INGEST_LOCK (
    LOCK_ID NUMBER NOT NULL,
    OWNER VARCHAR,
    ACQUIRED_AT TIMESTAMP_LTZ
);

INSERT INTO INGEST_LOCK (LOCK_ID) VALUES (1);

CREATE TABLE INGEST_RUNS (
    RUN_ID VARCHAR NOT NULL,
    STATUS VARCHAR NOT NULL,
    CONFIG_HASH VARCHAR NOT NULL,
    NEXT_PAGE NUMBER NOT NULL DEFAULT 0,
    RECORDS_LOADED NUMBER NOT NULL DEFAULT 0,
    EXPECTED_PAGES NUMBER,
    EXPECTED_RECORDS NUMBER,
    PAGE_SIZE NUMBER,
    ERROR_CODE VARCHAR,
    NEXT_ATTEMPT_AT TIMESTAMP_LTZ,
    STARTED_AT TIMESTAMP_LTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_LTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    COMPLETED_AT TIMESTAMP_LTZ
);

CREATE TABLE RAW_RECORDS (
    RUN_ID VARCHAR NOT NULL,
    PAGE_NUMBER NUMBER NOT NULL,
    RECORD_INDEX NUMBER NOT NULL,
    PAYLOAD VARIANT NOT NULL,
    INGESTED_AT TIMESTAMP_LTZ NOT NULL DEFAULT CURRENT_TIMESTAMP()
);

CREATE VIEW HISTORY_RECORDS AS
SELECT records.*, runs.STARTED_AT, runs.COMPLETED_AT
FROM RAW_RECORDS records
JOIN INGEST_RUNS runs ON records.RUN_ID = runs.RUN_ID
WHERE runs.STATUS = 'COMPLETED';

CREATE VIEW LATEST_RECORDS AS
WITH latest_run AS (
    SELECT RUN_ID
    FROM INGEST_RUNS
    WHERE STATUS = 'COMPLETED'
    QUALIFY ROW_NUMBER() OVER (ORDER BY COMPLETED_AT DESC, RUN_ID DESC) = 1
)
SELECT records.*
FROM RAW_RECORDS records
JOIN latest_run ON records.RUN_ID = latest_run.RUN_ID;

CREATE NETWORK RULE QUERY_API_NETWORK
    MODE = EGRESS
    TYPE = HOST_PORT
    VALUE_LIST = ({{HOST_LIST}});

CREATE SECRET QUERY_API_PAT
    TYPE = GENERIC_STRING
    SECRET_STRING = 'NOT_CONFIGURED';

CREATE EXTERNAL ACCESS INTEGRATION QUERY_API_STARTER_EAI
    ALLOWED_NETWORK_RULES = (QUERY_API_STARTER.INGEST.QUERY_API_NETWORK)
    ALLOWED_AUTHENTICATION_SECRETS = (QUERY_API_STARTER.INGEST.QUERY_API_PAT)
    ENABLED = TRUE;

CREATE PROCEDURE INGEST_QUERY_API()
RETURNS VARIANT
LANGUAGE PYTHON
RUNTIME_VERSION = '3.12'
PACKAGES = ('snowflake-snowpark-python', 'requests')
HANDLER = 'main'
EXTERNAL_ACCESS_INTEGRATIONS = (QUERY_API_STARTER_EAI)
SECRETS = ('api_pat' = QUERY_API_STARTER.INGEST.QUERY_API_PAT)
EXECUTE AS OWNER
AS
$${{PYTHON_SOURCE}}$$;

CREATE TASK QUERY_API_POLL
    SCHEDULE = '60 MINUTE'
    USER_TASK_MANAGED_INITIAL_WAREHOUSE_SIZE = 'XSMALL'
    SERVERLESS_TASK_MIN_STATEMENT_SIZE = 'XSMALL'
    SERVERLESS_TASK_MAX_STATEMENT_SIZE = 'XSMALL'
    USER_TASK_TIMEOUT_MS = 300000
    STATEMENT_TIMEOUT_IN_SECONDS = 300
    SUSPEND_TASK_AFTER_NUM_FAILURES = 3
AS CALL QUERY_API_STARTER.INGEST.INGEST_QUERY_API();
